first_project/first_app/urls.py
from django.urls import path
from . import views
app_name='first_app'
urlpatterns = [
    # path('',views.index,name='index'),
    path('webdetails/',views.webdetails,name='webdetails'),
    path('registration/',views.register,name='registration'),
    path('user_login/',views.user_login,name='user_login'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special_welcome,name='special'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from first_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('first_app/',include('first_app.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    top_name=models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    name=models.CharField(max_length=200,unique=True)
    url=models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    webpageName=models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date=models.DateField()

    def __str__(self):
        return str(self.date)

# class Register(models.Model):
#     name=models.CharField(max_length=500)
#     email=models.EmailField()
#     confirm_email=models.EmailField()
#     password=models.CharField(max_length=50)
#     confirm_password=models.CharField(max_length=50)
#     comments=models.CharField(max_length=5000)
#
#     def __str__(self):
#         return self.name

class UserProfileInfo(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.core import validators
# from first_app.models import Register
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo
# Create you own custom validators
#
# def check_for_name(value):
#     if value[0].lower() !='z' : raise forms.ValidationError('Name Needs to start with z')
#
# class Registration(forms.ModelForm):
#     class Meta():
#         model=Register
#         fields='__all__'
#         widget={
#         'password':forms.PasswordInput,
#         'confirm_password':forms.PasswordInput
#         }
#
#

#

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    confirm_email=forms.EmailField()
    class Meta():
        model=User
        fields=('username','email','confirm_email','password','confirm_password')


    def clean(self):
        ## verify the emails
        data=super().clean()
        print(data)
        if data['email'] != data['confirm_email']: raise forms.ValidationError("Email does not match!")
        if data['password'] != data['confirm_password']: raise forms.ValidationError("Password does not match!")
        try:
            db_email=Register.objects.get(email=data['email'])
            if db_email: raise forms.ValidationError("Email Already Exists! Please Try Login")

        except:
            print('This is new Email!')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('portfolio_site','profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Webpage,AccessRecord
from . import forms
from itertools import chain

# Extra import for login and logout
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



def index(request):
    return render(request,'first_app/index.html')

def register(request):

    registered=False

    if request.method=='POST':
        user_form=forms.UserForm(data=request.POST)
        profile_form=forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form=forms.UserForm()
        profile_form=forms.UserProfileInfoForm()

    return render(request,'first_app/registration.html',context={'user_form':user_form,
                                                                 'profile_form':profile_form,
                                                                 'registered': registered})
@login_required
def special_welcome(request):
    return HttpResponse("You have logged in Successfully")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method=='POST':
        username=request.POST.get('user_name')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)


        if user:
            if user.is_active:
                login(request, user)
                print(reverse('index'))
                return HttpResponseRedirect(reverse('index'))
            else:
                HttpResponse("YOUR ACCCOUNT IS NOT ACTIVE!")
        else:
            print('Someone Tried to login, but failed!')
            print('Username: {username} and password: {password} is used'.format(username,password))
            return HttpResponse("Invalid login.Either username or password is incorrect!")

    else:
        return render(request,'first_app/login.html')









def webdetails(request):
    acc_record= AccessRecord.objects.order_by('date')
    webpages=Webpage.objects.all()
    for acc in acc_record:
        acc_record.wepages=Webpage.objects.filter(name=acc.webpageName)


    # for web in webpages:
    #     print(web.date)

    context_dic={'AccessRecords':acc_record,'webpages':webpages}
    return render(request,'first_app/webdetails.html',context=context_dic)






# Create your views here.

first_project/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "first_app/css/style.css"%}">
  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
     <div class="container">
       <ul class="navbar-nav">
         <li class="nav-brand"><a href="{% url 'index'%}" class="nav-link">BRAND</a></li>
         <li class="nav-item"><a href="{% url 'admin:index'%}" class="nav-link">Admin</a></li>
         <li class="nav-item"><a href="{% url 'first_app:registration' %}" class="nav-link">Registration</a></li>
         {% if user.is_authenticated %}
         <li class="nav-item"><a href="{% url 'first_app:logout' %}" class="nav-link">Logout</a></li>
         {% else %}
         <li class="nav-item"><a href="{% url 'first_app:user_login' %}" class="nav-link">Login</a></li>

         {% endif %}

         <li class="nav-item"><a href="{% url 'first_app:webdetails' %}" class="nav-link">Access Records</a></li>
       </ul>
     </div>
   </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>

  </body>
</html>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends 'first_app/base.html' %}
<!-- {% load staticfiles %} -->
   {% block body_block %}
    <h1>Welcome to Django project!</h1>

    {% endblock %} -->

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Please Login Here!</h1>
  <form action="{% url 'first_app:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="user_name">UserName:</label>
    <input type="text" name="user_name" placeholder="Enter Username">
    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>
{% endblock %}

first_project/templates/first_app/registration.html
{% extends 'first_app/base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registring!</h1>

  {% else %}
  <h1>Register Here,Fill out below Form</h1>
  <form  enctype="multipart/form-data"  method="POST">
    {% csrf_token %}
    {% for frm in user_form %}
    <div class="form-group">
    <label>{{frm.label}}</label>
    <br>
     {{frm}}
     <br>
    {% endfor %}
    </div>
    <!-- {{ user_form.as_p }} -->
    <!-- {{ profile_form.as_p }} -->
    <br>
    <input class="btn btn-primary" type="submit" name="Register" value="Register">
  </form>
  {% endif %}
</div>


 {% endblock %}

first_project/templates/first_app/webdetails.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Topic Details Access</title>
  </head>
  <body>
    <div class="">
      {% if AccessRecords %}
      <table border=2>
        <thead>
          <th>WebpageName</th>
          <th>Date Accessed</th>
          <th>URL</th>
        </thead>

        {% for acc_rec in AccessRecords %}
           <tr>
             <td>{{ acc_rec.webpageName}}</td>
             <td>{{acc_rec.date}}</td>
             <td>{{acc_rec.wepages}}</td>
           </tr>


        {% endfor %}
      </table>
      {% endif %}
    </div>
  </body>
</html>